apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: fastapi-app
  source:
    repoURL: "https://github.com/tejamahesh1433/devopsforge-10c-test.git"
    targetRevision: "main"
    path: "helm/fastapi-app"
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-app-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
