apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fastapi-app
  namespace: argocd
spec:
  description: DevOpsForge Project for fastapi-app
  sourceRepos:
    - "https://github.com/tejamahesh1433/devopsforge-10c-test.git"
  destinations:
    - namespace: fastapi-app-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
